-- Verificar datos de TRAMA REDUZIDO
SELECT 
  "ARTIGO CODIGO", 
  "NOME DE MERCADO",
  SUBSTRING("TRAMA REDUZIDO", 1, 30) AS "TRAMA"
FROM tb_FICHAS 
WHERE "ARTIGO CODIGO" IN ('AI311102G5561', 'YI310847G5561', 'YIC20949C5920')
LIMIT 5;

-- Contar registros con TRAMA
SELECT 
  COUNT(*) AS total,
  COUNT("TRAMA REDUZIDO") AS con_trama,
  COUNT(*) - COUNT("TRAMA REDUZIDO") AS sin_trama
FROM tb_FICHAS;
