-- Script para cambiar todos los VARCHAR a TEXT en tablas de producción
-- Esto evita errores "value too long for type character varying(N)"

-- tb_FICHAS
ALTER TABLE tb_FICHAS ALTER COLUMN ARTIGO TYPE TEXT;
ALTER TABLE tb_FICHAS ALTER COLUMN DESCRICAO TYPE TEXT;
ALTER TABLE tb_FICHAS ALTER COLUMN COMPOSICAO TYPE TEXT;
ALTER TABLE tb_FICHAS ALTER COLUMN LARGURA_CM TYPE TEXT;
ALTER TABLE tb_FICHAS ALTER COLUMN GRAMATURA TYPE TEXT;

-- tb_RESIDUOS_INDIGO  
ALTER TABLE tb_RESIDUOS_INDIGO ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_RESIDUOS_INDIGO ALTER COLUMN TURNO TYPE TEXT;
ALTER TABLE tb_RESIDUOS_INDIGO ALTER COLUMN LOTE TYPE TEXT;
ALTER TABLE tb_RESIDUOS_INDIGO ALTER COLUMN DATA_PRODUCAO TYPE TEXT;
ALTER TABLE tb_RESIDUOS_INDIGO ALTER COLUMN TIPO TYPE TEXT;
ALTER TABLE tb_RESIDUOS_INDIGO ALTER COLUMN PESO_KG TYPE TEXT;

-- tb_RESIDUOS_POR_SECTOR
ALTER TABLE tb_RESIDUOS_POR_SECTOR ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_RESIDUOS_POR_SECTOR ALTER COLUMN DATA_REF TYPE TEXT;
ALTER TABLE tb_RESIDUOS_POR_SECTOR ALTER COLUMN SETOR TYPE TEXT;
ALTER TABLE tb_RESIDUOS_POR_SECTOR ALTER COLUMN TIPO_RESIDUO TYPE TEXT;
ALTER TABLE tb_RESIDUOS_POR_SECTOR ALTER COLUMN PESO_KG TYPE TEXT;

-- tb_TESTES
ALTER TABLE tb_TESTES ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_TESTES ALTER COLUMN TURNO TYPE TEXT;
ALTER TABLE tb_TESTES ALTER COLUMN DATA_TESTE TYPE TEXT;
ALTER TABLE tb_TESTES ALTER COLUMN TIPO_TESTE TYPE TEXT;
ALTER TABLE tb_TESTES ALTER COLUMN RESULTADO TYPE TEXT;

-- tb_PARADAS  
ALTER TABLE tb_PARADAS ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_PARADAS ALTER COLUMN DATA_PARADA TYPE TEXT;
ALTER TABLE tb_PARADAS ALTER COLUMN TURNO TYPE TEXT;
ALTER TABLE tb_PARADAS ALTER COLUMN MAQUINA TYPE TEXT;
ALTER TABLE tb_PARADAS ALTER COLUMN MOTIVO TYPE TEXT;
ALTER TABLE tb_PARADAS ALTER COLUMN MINUTOS TYPE TEXT;

-- tb_PRODUCCION (tabla principal con muchas columnas)
ALTER TABLE tb_PRODUCCION ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN DT_INICIO TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN HORA_INICIO TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN DT_FINAL TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN HORA_FINAL TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN DT_BASE_PRODUCAO TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN TURNO TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN PARTIDA TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN PARTIDA_DUPLA TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN R TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN ARTIGO TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN COR TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN METRAGEM TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "METRAGEM ENCOLH" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN TEMPO TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "VELOC CALC" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN VELOC TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN EFICIENCIA TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN NUM_FIOS TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN S TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN MAQUINA TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN RUPTURAS TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN CAVALOS TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN OPERADOR TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "NM OPERADOR" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "NM MERCADO" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "LARG PAD" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "LARG INI" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "LARG FIM" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "TRAMA REDUZIDA 1" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "TRAMA REDUZIDA 2" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "RUP FIACAO" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "RUP URD" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "RUP OPER" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "LOTE FIACAO" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN "MAQ  FIACAO" TYPE TEXT;
ALTER TABLE tb_PRODUCCION ALTER COLUMN ROLADA TYPE TEXT;

-- tb_CALIDAD
ALTER TABLE tb_CALIDAD ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN DT_BASE TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN TURNO TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN "MAQUINA PR" TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN PARTIDA TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN "METROS AC" TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN "PRIMETROS ACRODUÇÃO" TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN "PERC METROS AC" TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN "TOTAL PONTOS" TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN ARTIGO TYPE TEXT;
ALTER TABLE tb_CALIDAD ALTER COLUMN COR TYPE TEXT;

-- tb_DEFECTOS
ALTER TABLE tb_DEFECTOS ALTER COLUMN CODIGO TYPE TEXT;
ALTER TABLE tb_DEFECTOS ALTER COLUMN DESCRIPCION TYPE TEXT;
ALTER TABLE tb_DEFECTOS ALTER COLUMN CATEGORIA TYPE TEXT;

-- tb_CALIDAD_FIBRA
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN DATA_ENTRADA TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN FORNECEDOR TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN LOTE TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN FARDO TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN MICRONAIRE TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN STRENGTH TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN LENGTH TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN UNIFORMITY TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN ELONGATION TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN COLOR_RD TYPE TEXT;
ALTER TABLE tb_CALIDAD_FIBRA ALTER COLUMN COLOR_B TYPE TEXT;

-- tb_PRODUCCION_OE  
ALTER TABLE tb_PRODUCCION_OE ALTER COLUMN FILIAL TYPE TEXT;
ALTER TABLE tb_PRODUCCION_OE ALTER COLUMN DT_BASE TYPE TEXT;
ALTER TABLE tb_PRODUCCION_OE ALTER COLUMN TURNO TYPE TEXT;
ALTER TABLE tb_PRODUCCION_OE ALTER COLUMN MAQUINA TYPE TEXT;
ALTER TABLE tb_PRODUCCION_OE ALTER COLUMN PRODUCAO_KG TYPE TEXT;
