CREATE TABLE [tb_PARADAS] (
    [FILIAL] INTEGER,
    [MAQUINA] INTEGER,
    [TP_MAQ] INTEGER,
    [PROCESSO] TEXT,
    [DATA_BASE] TEXT,
    [HORA_INICIO] TEXT,
    [HORA_FINAL] TEXT,
    [TURNO] TEXT,
    [DURACAO] INTEGER,
    [NUM OCORREN] INTEGER,
    [OPERADOR] INTEGER,
    [NOME_OPER] TEXT,
    [MOTIVO] INTEGER,
    [DESC_MOTIVO] TEXT,
    [GRUPO] INTEGER,
    [DESC_GRP_MOTIVO] TEXT,
    [CAUSA] TEXT,
    [DESC_CAUSA] TEXT,
    [LADO] TEXT,
    [POSICAO] TEXT,
    [PARTIDA] TEXT,
    [URDUME] TEXT,
    [INDIGO] TEXT,
    [DATA_TINGIMENT] TEXT,
    [TURNO_TING] TEXT,
    [STATUS_INDIG] TEXT,
    [OPER_TING] TEXT,
    [NOME_OPER_TING] TEXT,
    [GRUPO_MAQ] INTEGER,
    [OBS] TEXT,
    [PARTIDA_ORIGINAL] TEXT,
    [CV_ORIG] TEXT,
    [ST_ORIG] TEXT,
    [OBS_ORIG] TEXT,
    [PARTIDA_ANTERIOR] TEXT,
    [CV_ANT] TEXT,
    [ST_ANT] TEXT,
    [OBS_ANT] TEXT,
    [PARTIDA_POSTERIOR] TEXT,
    [CV_POS] TEXT,
    [ST_POS] TEXT,
    [OBS_POS] TEXT,
    [ROLADA] TEXT,
    [ID TROCA ROLADA] TEXT,
    [MOTIVO1] TEXT,
    [DESCRICAO MOTIVO] TEXT,
    [ROLADA INICIAL] TEXT,
    [COR] TEXT,
    [ROLADA FINAL] TEXT,
    [COR1] TEXT,
    [OBS TROCA ROLADA] TEXT,
    [TEMPO PREVISTO] TEXT,
    [SUB-GRUPO] TEXT,
    [DESC SUB-GRUPO] TEXT
);
CREATE TABLE [tb_RESIDUOS_INDIGO] (
    [FILIAL] INTEGER,
    [SETOR] INTEGER,
    [DESC_SETOR] TEXT,
    [DT_MOV] TEXT,
    [TURNO] TEXT,
    [SUBPRODUTO] INTEGER,
    [DESCRICAO] TEXT,
    [ID] INTEGER,
    [PESO LIQUIDO (KG)] INTEGER,
    [LOTE] TEXT,
    [PARTIDA] TEXT,
    [ROLADA] INTEGER,
    [MOTIVO] TEXT,
    [DESC_MOTIVO] TEXT,
    [OPERADOR] INTEGER,
    [NOME_OPER] TEXT,
    [PE DE ROLO] TEXT,
    [INDIGO] INTEGER,
    [URDUME] TEXT,
    [TURNO CORTE] TEXT,
    [GAIOLA] INTEGER,
    [OBS] TEXT,
    [PESO ROLO 01] TEXT,
    [PESO ROLO 02] TEXT,
    [PESO ROLO 03] TEXT,
    [PESO ROLO 04] TEXT,
    [PESO ROLO 05] TEXT,
    [PESO ROLO 06] TEXT,
    [PESO ROLO 07] TEXT,
    [PESO ROLO 08] TEXT,
    [PESO ROLO 09] TEXT,
    [PESO ROLO 10] TEXT,
    [PESO ROLO 11] TEXT,
    [PESO ROLO 12] TEXT,
    [PESO ROLO 13] TEXT,
    [PESO ROLO 14] TEXT,
    [PESO ROLO 15] TEXT,
    [PESO ROLO 16] TEXT,
    [DEVOL TEC#] TEXT
);
CREATE TABLE [tb_RESIDUOS_POR_SECTOR] (
    [FILIAL] INTEGER,
    [SETOR] INTEGER,
    [DESC_SETOR] TEXT,
    [DT_MOV] TEXT,
    [TURNO] TEXT,
    [SUBPRODUTO] INTEGER,
    [DESCRICAO] TEXT,
    [ID] INTEGER,
    [PESO LIQUIDO (KG)] INTEGER,
    [LOTE] TEXT,
    [OPERADOR] INTEGER,
    [NOME_OPER] TEXT,
    [OBS] TEXT
);
CREATE TABLE [tb_TESTES] (
    [MAQUINA] INTEGER,
    [ARTIGO] TEXT,
    [NM_MERC] TEXT,
    [PARTIDA] INTEGER,
    [METRAGEM] INTEGER,
    [DT_PROD] TEXT,
    [HORA_PROD] TEXT,
    [TURNO] TEXT,
    [LARG_AL] INTEGER,
    [GRAMAT] INTEGER,
    [POTEN] INTEGER,
    [%_ENC_URD] INTEGER,
    [%_ENC_TRAMA] INTEGER,
    [%_SK1] INTEGER,
    [%_SK2] INTEGER,
    [%_SK3] INTEGER,
    [%_SK4] INTEGER,
    [%_SKE] INTEGER,
    [%_STT] INTEGER,
    [%_SKM] INTEGER,
    [APROV] INTEGER,
    [COD_ART] INTEGER,
    [COR_ART] INTEGER,
    [OBS] INTEGER,
    [REPROCESSO] INTEGER,
    [SEQ TESTE] INTEGER
);
CREATE TABLE import_control (
  tabla_destino TEXT PRIMARY KEY,
  xlsx_path TEXT NOT NULL,
  xlsx_sheet TEXT NOT NULL,
  last_import_date TEXT NOT NULL,  -- ISO 8601: yyyy-MM-dd HH:mm:ss
  xlsx_last_modified TEXT NOT NULL, -- Fecha de modificaci├│n del archivo XLSX
  xlsx_hash TEXT NOT NULL,          -- MD5 hash del archivo para detectar cambios
  rows_imported INTEGER NOT NULL,
  mapping_json_path TEXT,
  date_column TEXT,                 -- NULL si usa -ClearTable
  import_strategy TEXT NOT NULL,    -- 'date_delete' o 'clear_table'
  notes TEXT
);
CREATE TABLE tb_CALIDAD ([EMP] TEXT, [DAT_PROD] TEXT, [GRP_DEF] TEXT, [COD_DE] TEXT, [DEFEITO] TEXT, [INDIGO] TEXT, [CC] TEXT, [GRP_TEAR] TEXT, [TEAR] TEXT, [ARTIGO] TEXT, [COR] TEXT, [PARTIDA] TEXT, [G_CMEST] TEXT, [ACONDIC] TEXT, [GRP_TEC] TEXT, [TRAMA] TEXT, [ROLADA] TEXT, [METRAGEM] TEXT, [QUALIDADE] TEXT, [PESO BRUTO] TEXT, [REVISOR FINAL] TEXT, [HORA] TEXT, [NM MERC] TEXT, [TUR TEC] TEXT, [T TEC1] TEXT, [T TEC2] TEXT, [EMENDAS] TEXT, [PE├çA] TEXT, [ETIQUETA] TEXT, [PESO LIQUIDO] TEXT, [LARGURA] TEXT, [GR/M2] TEXT, [T INDIGO] TEXT, [PONTUACAO] TEXT, [REPROCESSO] TEXT, [COD DIREC] TEXT, [DESC DIREC] TEXT, [DT INI TEC] TEXT, [HR INI TEC] TEXT, [DT FIM TEC] TEXT, [HR FIM TEC] TEXT, [RPM TECEL] TEXT, [GRUPO CMESTR] TEXT, [URDUME] TEXT, [MODELO TEAR] TEXT, [ST IND] TEXT, [G#PR] TEXT, [DT  TINGIMENTO] TEXT, [TURNO INDIGO] TEXT, [OPER INDIGO] TEXT, [LAVADEIRA 01] TEXT, [TURNO LAVAD ] TEXT, [LAVADEIRA 02] TEXT, [TURNO LAVAD 1] TEXT, [LAVADEIRA 03] TEXT, [TURNO LAVAD 03] TEXT, [INTEGRADA] TEXT, [TURNO INTEGR] TEXT, [SANFOR 01] TEXT, [TURNO SANF 01] TEXT, [SANFOR 02] TEXT, [TURNO SANF 02] TEXT, [CALANDRA] TEXT, [TURNO CALAND] TEXT, [ESTAMAPRIA] TEXT, [TURNO ESTAMP] TEXT, [MERCERZ 01] TEXT, [TURNO MERC 01] TEXT, [MERCERZ 02] TEXT, [TURNO MERC 02] TEXT, [DATA PESAGEM] TEXT, [HORA PESAGEM] TEXT, [TURNO PESAGEM ] TEXT, [LOCAL TECEL] TEXT, [DEF EMENDA] TEXT, [DESC DEF EMENDA] TEXT, [HORARIO_REVISAO] TEXT, [TURNO_HORARIO_REVISAO] TEXT, [TURNO_REVISAO] TEXT, [DATA_REVISAO] TEXT, [REVISOR EMENDA] TEXT, [HORA PECA FINAL] TEXT, [TURNO PECA FINAL] TEXT, 'G.PR' TEXT, 'TURNO LAVAD' TEXT, 'TURNO PESAGEM' TEXT, 'DEFEITO MANCHA' TEXT);
CREATE TABLE tb_PRODUCCION (
  "FILIAL" TEXT,
  "DT_INICIO" TEXT,
  "HORA_INICIO" TEXT,
  "DT_FINAL" TEXT,
  "HORA_FINAL" TEXT,
  "DT_BASE_PRODUCAO" TEXT,
  "TURNO" TEXT,
  "PARTIDA" TEXT,
  "PARTIDA_DUPLA" TEXT,
  "R" TEXT,
  "ARTIGO" TEXT,
  "COR" TEXT,
  "METRAGEM" TEXT,
  "METRAGEM ENCOLH" TEXT,
  "TEMPO" TEXT,
  "VELOC CALC" TEXT,
  "VELOC" TEXT,
  "EFICIENCIA" TEXT,
  "NUM_FIOS" TEXT,
  "S" TEXT,
  "MAQUINA" TEXT,
  "RUPTURAS" TEXT,
  "CAVALOS" TEXT,
  "OPERADOR" TEXT,
  "NM OPERADOR" TEXT,
  "NM MERCADO" TEXT,
  "LARG PAD" TEXT,
  "LARG INI" TEXT,
  "LARG FIM" TEXT,
  "TRAMA REDUZIDA 1" TEXT,
  "TRAMA REDUZIDA 2" TEXT,
  "RUP FIACAO" TEXT,
  "RUP URD" TEXT,
  "RUP OPER" TEXT,
  "LOTE FIACAO" TEXT,
  "MAQ  FIACAO" TEXT,
  "ROLADA" TEXT,
  "SELETOR" TEXT,
  "QTDE_RUPTURA" TEXT,
  "COD_RUP" TEXT,
  "MOTIVO_RUP" TEXT,
  "TIPO_RUP" TEXT,
  "DESC_TP_RUPTURA" TEXT,
  "COD_CAVALO" TEXT,
  "DESC_CAVALO" TEXT,
  "QTDE_CAVALO" TEXT,
  "PONTOS_LIDOS" TEXT,
  "PONTOS_100%" TEXT,
  "BATIDAS" TEXT,
  "ENCOLH ACAB" TEXT,
  "ESTIRAGEM REVISAO" TEXT,
  "TEMPO LEIT MIN" TEXT,
  "TOTAL MINUTOS TUR " TEXT,
  "TOTAL MINUTOS TUR 1" TEXT,
  "TOTAL MINUTOS TUR 2" TEXT,
  "PARADA TEC TRAMA" TEXT,
  "PARADA TEC URDUME" TEXT,
  "PARADA TEC OUTROS" TEXT,
  "PARADA TEC STOP" TEXT,
  "BASE URDUME" TEXT,
  "RPM LEITURA" TEXT,
  "RPM NOMINALTEAR" TEXT,
  "GRUPO TEAR" TEXT,
  "DESC TEAR" TEXT,
  "MODELO TEAR" TEXT,
  "MAQ INDIGO" TEXT
);
CREATE TABLE sqlite_stat1(tbl,idx,stat);
CREATE TABLE tb_PROCESO (
  FILIAL TEXT,
  PROCESSO TEXT,
  PARTIDA TEXT,
  ARTIGO TEXT,
  COR TEXT,
  DESC_NM_MERC TEXT,
  MT_DISPONIV TEXT,
  DT_PROD TEXT,
  NUM_FIOS TEXT,
  FLANGE TEXT,
  LADO TEXT,
  MAQUINA TEXT,
  STATUS TEXT,
  URDUME TEXT,
  MT_PREVISTA TEXT,
  MT_A_BATER TEXT,
  MT_PROX24H TEXT,
  BATIDAS TEXT,
  RPM TEXT,
  EFIC_TA TEXT,
  EFIC_TB TEXT,
  EFIC_TC TEXT,
  EFIC_DIA TEXT,
  ART_PROGR TEXT,
  NM_MERC_PROG TEXT,
  COR_PG TEXT,
  URDUME_PRO TEXT,
  GRUPO_TEAR TEXT,
  REPROCESSO TEXT,
  LARGURA TEXT,
  TRAMA_REDUZIDA_1 TEXT,
  TRAMA_REDUZIDA_2 TEXT,
  "DATA FINAL TECEL" TEXT,
  HORA_FINAL_TECEL TEXT,
  TURNO_FINAL_TECE TEXT,
  HORA_FINAL_TECEL_V2 TEXT,
  "OBS ACABAMENTO" TEXT,
  "COD MOT REP" TEXT,
  "MOTIVO REPROCESSO" TEXT,
  "OBS REPROCESSO" TEXT
);
CREATE TABLE tb_DEFECTOS (FILIAL TEXT, PARTIDA TEXT, PECA TEXT, ETIQUETA TEXT, ARTIGO TEXT, NM_MERC TEXT, COD_DEF TEXT, DESC_DEFEITO TEXT, PONTOS TEXT, QUALIDADE TEXT, DATA_PROD TEXT);
CREATE TABLE tb_COSTO_ITEMS (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      codigo TEXT NOT NULL UNIQUE,
      descripcion TEXT NOT NULL,
      unidad TEXT NOT NULL DEFAULT 'KG',
      activo INTEGER NOT NULL DEFAULT 1
    );
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE tb_COSTO_ITEM_ALIAS (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      item_id INTEGER NOT NULL,
      origen TEXT NOT NULL,
      nombre_en_origen TEXT NOT NULL,
      FOREIGN KEY (item_id) REFERENCES tb_COSTO_ITEMS(id),
      UNIQUE (origen, nombre_en_origen)
    );
CREATE TABLE tb_COSTO_MENSUAL (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      yyyymm TEXT NOT NULL,
      item_id INTEGER NOT NULL,
      ars_por_unidad REAL NOT NULL, observaciones TEXT,
      FOREIGN KEY (item_id) REFERENCES tb_COSTO_ITEMS(id),
      UNIQUE (yyyymm, item_id)
    );
CREATE INDEX idx_import_control_last_import 
ON import_control(last_import_date);
CREATE INDEX idx_calidad_dat_prod ON tb_CALIDAD(DAT_PROD);
CREATE INDEX idx_calidad_rolada ON tb_CALIDAD(ROLADA);
CREATE INDEX idx_calidad_tear ON tb_CALIDAD(TEAR);
CREATE INDEX idx_calidad_qualidade ON tb_CALIDAD(QUALIDADE);
CREATE INDEX idx_calidad_artigo ON tb_CALIDAD(ARTIGO);
CREATE INDEX idx_produccion_dt_base ON tb_PRODUCCION(DT_BASE_PRODUCAO);
CREATE INDEX idx_produccion_artigo ON tb_PRODUCCION(ARTIGO);
CREATE INDEX idx_produccion_partida ON tb_PRODUCCION(PARTIDA);
CREATE INDEX idx_produccion_seletor ON tb_PRODUCCION(SELETOR);
CREATE INDEX idx_testes_artigo ON tb_TESTES(ARTIGO);
CREATE INDEX idx_paradas_data ON tb_PARADAS(DATA_BASE);
CREATE INDEX idx_calidad_revisor_fecha ON tb_CALIDAD('REVISOR FINAL', DAT_PROD);
CREATE INDEX idx_calidad_partida ON tb_CALIDAD(PARTIDA);
CREATE INDEX idx_produccion_seletor_filial ON tb_PRODUCCION(SELETOR, FILIAL);
CREATE INDEX idx_calidad_revisor ON tb_CALIDAD("REVISOR FINAL");
CREATE INDEX idx_calidad_partida_dat_revisor ON tb_CALIDAD(PARTIDA, DAT_PROD, "REVISOR FINAL");
CREATE INDEX idx_produccion_partida_dt ON tb_PRODUCCION(PARTIDA, DT_BASE_PRODUCAO);
CREATE INDEX idx_produccion_composite ON tb_PRODUCCION(FILIAL, SELETOR, DT_BASE_PRODUCAO, PARTIDA) 
  WHERE PARTIDA IS NOT NULL AND PARTIDA != '';
CREATE INDEX idx_testes_dt_prod ON tb_TESTES(DT_PROD);
CREATE INDEX idx_proceso_partida ON tb_PROCESO(PARTIDA);
CREATE INDEX idx_proceso_dt_prod ON tb_PROCESO(DT_PROD);
CREATE INDEX idx_proceso_maquina ON tb_PROCESO(MAQUINA);
CREATE INDEX idx_produccion_base_urdume ON tb_PRODUCCION ([BASE URDUME]);
CREATE INDEX idx_residuos_dt_mov ON tb_RESIDUOS_INDIGO (DT_MOV);
CREATE INDEX idx_residuos_descricao ON tb_RESIDUOS_INDIGO (DESCRICAO);
CREATE INDEX idx_produccion_base_urdume_trim ON tb_PRODUCCION (TRIM([BASE URDUME]));
CREATE INDEX idx_residuos_sector_dt_mov ON tb_RESIDUOS_POR_SECTOR (DT_MOV);
CREATE INDEX idx_residuos_sector_descricao ON tb_RESIDUOS_POR_SECTOR (DESCRICAO);
CREATE INDEX idx_costo_mensual_mes ON tb_COSTO_MENSUAL(yyyymm);
CREATE INDEX idx_costo_alias_item ON tb_COSTO_ITEM_ALIAS(item_id);
CREATE INDEX idx_produccion_seletor_rolada ON tb_PRODUCCION(SELETOR, ROLADA) WHERE ROLADA IS NOT NULL AND ROLADA != '';
CREATE INDEX idx_produccion_urdideira_partida ON tb_PRODUCCION(ROLADA, PARTIDA) WHERE SELETOR='URDIDEIRA' AND PARTIDA IS NOT NULL;
CREATE INDEX idx_calidad_rolada_emp ON tb_CALIDAD(ROLADA, EMP) WHERE ROLADA IS NOT NULL AND ROLADA != '';
CREATE INDEX idx_calidad_rolada_qualidade ON tb_CALIDAD(ROLADA, QUALIDADE, EMP) WHERE ROLADA IS NOT NULL;
CREATE INDEX idx_produccion_indigo_dtinicio ON tb_PRODUCCION(DT_INICIO) WHERE SELETOR='INDIGO';
CREATE INDEX idx_produccion_tecelagem_rolada ON tb_PRODUCCION(SELETOR, ROLADA) WHERE SELETOR='TECELAGEM' AND ROLADA IS NOT NULL;
CREATE INDEX idx_produccion_indigo_partida_s ON tb_PRODUCCION(ROLADA, PARTIDA, S) WHERE SELETOR='INDIGO' AND PARTIDA IS NOT NULL AND S IS NOT NULL;
CREATE TABLE tb_METAS (

    id INTEGER PRIMARY KEY AUTOINCREMENT,

    Dia DATE NOT NULL UNIQUE,

    Indigo REAL,

    Meta_Eficiencia_INDIGO REAL,

    Meta_Rotura_INDIGO REAL,

    Meta_Estopa_Azul REAL,

    Tejeduria REAL,

    RU105 REAL,

    RT105 REAL,

    EFI_Percent REAL,

    Meta_Estopa_Azul_Tejeduria REAL,

    Integrada REAL,

    Meta_Velocidad_Integrada REAL,

    Meta_ENC_URD_Integrada REAL,

    Revision REAL,

    Dia_Invertido INTEGER,

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP

);
CREATE INDEX idx_metas_dia ON tb_METAS(Dia);
CREATE TABLE tb_CALIDAD_FIBRA (
  ITEM TEXT,
  DESC_ITEM TEXT,
  ID TEXT,
  DATA_MOVIMENTO TEXT,
  TIPO_MOV TEXT,
  PRODUTOR TEXT,
  PROCED TEXT,
  LOTE TEXT,
  PILHA TEXT,
  DESTINO TEXT,
  COR TEXT,
  TP_MIC TEXT,
  TP TEXT,
  CLASSIFIC TEXT,
  LOTE_INTERNO TEXT,
  CORTEZA TEXT,
  QTDE REAL,
  MISTURA TEXT,
  SEQ TEXT,
  TIPO_MP TEXT,
  FORNECEDOR TEXT,
  NMFORN TEXT,
  NF TEXT,
  LOTE_FIAC TEXT,
  TAM TEXT,
  SCI REAL,
  MST REAL,
  MIC REAL,
  MAT REAL,
  UHML REAL,
  UI REAL,
  SF REAL,
  STR REAL,
  ELG REAL,
  RD REAL,
  PLUS_B REAL,
  TIPO TEXT,
  TrCNT REAL,
  TrAR REAL,
  TRID REAL,
  SAC TEXT,
  PIM TEXT,
  SC TEXT,
  BENF TEXT,
  TP_SELO TEXT,
  NUM_SELO TEXT,
  PESO REAL,
  PESO_MEDIO REAL,
  ENT_SAI TEXT,
  UM TEXT,
  OBSERVACAO TEXT,
  IDFIL TEXT,
  DT_EMISSAO TEXT,
  DT_ENTRADA_PROD TEXT,
  HR_ENTRADA_PROD TEXT,
  TURNO_ENT_PROD TEXT,
  LADO TEXT,
  FARDOS_TESTADOS TEXT,
  FORNECEDOR_2 TEXT,
  CONSIGNADO TEXT,
  LIBERADO TEXT,
  DATA_LIBERACAO TEXT,
  DOC_VENDA TEXT,
  DT_EMIS_DOC_VENDA TEXT,
  USU_LIBEROU TEXT,
  DT_INCLUSAO TEXT,
  USU_INCLUSAO TEXT,
  DT_ALTERACAO TEXT,
  USU_ALTERACAO TEXT
);
CREATE INDEX idx_calidad_fibra_data ON tb_CALIDAD_FIBRA(DATA_MOVIMENTO);
CREATE INDEX idx_calidad_fibra_lote ON tb_CALIDAD_FIBRA(LOTE);
CREATE INDEX idx_calidad_fibra_fornecedor ON tb_CALIDAD_FIBRA(FORNECEDOR);
CREATE INDEX idx_calidad_fibra_item ON tb_CALIDAD_FIBRA(ITEM);
CREATE TABLE import_column_warnings (id INTEGER PRIMARY KEY AUTOINCREMENT, tabla_destino TEXT NOT NULL, timestamp TEXT NOT NULL, csv_path TEXT NOT NULL, extra_columns TEXT, missing_columns TEXT, total_csv_columns INTEGER, total_table_columns INTEGER);
CREATE TABLE schema_changes_log (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      timestamp TEXT NOT NULL,
      tabla_destino TEXT NOT NULL,
      tipo_cambio TEXT NOT NULL,
      columna_afectada TEXT NOT NULL,
      tipo_dato TEXT,
      origen TEXT NOT NULL,
      usuario TEXT,
      csv_path TEXT,
      notas TEXT,
      estado TEXT DEFAULT 'APLICADO'
    );
CREATE INDEX idx_schema_changes_tabla ON schema_changes_log(tabla_destino);
CREATE INDEX idx_schema_changes_timestamp ON schema_changes_log(timestamp);
CREATE TABLE tb_PRODUCCION_OE (
    FILIAL TEXT,
    [LOC. FISICO] TEXT,
    MAQUINA TEXT,
    NOME_MAQUINA TEXT,
    DATA_PRODUCAO TEXT,
    TURNO TEXT,
    LADO TEXT,
    ITEM TEXT,
    [DESC ITEM] TEXT,
    [HORA INICIAL] TEXT,
    [HORA FINAL] TEXT,
    RPM TEXT,
    [NUM FUSOS] TEXT,
    ALFA TEXT,
    [LOTE PRODUC] TEXT,
    [T├ìTULO] TEXT,
    TEMPO TEXT,
    [TORCAO P POLEG] TEXT,
    [TORCAO P METRO] TEXT,
    [PROD MT/MIN] TEXT,
    [PROD KG/HR] TEXT,
    [PROD CALCULADA] TEXT,
    [PROD INFORMADA] TEXT,
    [EFIC CALCULADA] TEXT,
    [EFIC INFORMADA] TEXT,
    OPERADOR TEXT,
    [T.BOB.] TEXT,
    [RPM CARD] TEXT,
    N TEXT,
    S TEXT,
    L TEXT,
    T TEXT,
    MO TEXT,
    [CP V+ SL+] TEXT,
    [CM V- SL-] TEXT,
    [CCp C+] TEXT,
    [CCm C-] TEXT,
    [JP (P+)] TEXT,
    [JM (P-)] TEXT,
    CVP TEXT,
    CVM TEXT,
    [CORT NAT] TEXT,
    [% ROB 01] TEXT,
    [% ROB 02] TEXT,
    [% ROB 03] TEXT
);
CREATE INDEX idx_produccion_oe_fecha ON tb_PRODUCCION_OE(DATA_PRODUCAO);
CREATE INDEX idx_produccion_oe_maquina ON tb_PRODUCCION_OE(MAQUINA);
CREATE INDEX idx_produccion_oe_filial ON tb_PRODUCCION_OE(FILIAL);
CREATE INDEX idx_produccion_oe_turno ON tb_PRODUCCION_OE(TURNO);
CREATE TABLE [tb_FICHAS] (
    [ARTIGO CODIGO] TEXT,
    [ARTIGO] TEXT,
    [COR] TEXT,
    [NCM] INTEGER,
    [BASE] TEXT,
    [UnP] TEXT,
    [VENDA] TEXT,
    [PRODUCAO] TEXT,
    [NOME REDUZIDO] TEXT,
    [NOME DE MERCADO] TEXT,
    [LINHA] TEXT,
    [URDUME] TEXT,
    [SARJA] TEXT,
    [COD# RETALHO] TEXT,
    [SAP] TEXT,
    [TRAMA REDUZIDO] TEXT,
    [SGS] INTEGER,
    [SGS UN 1] INTEGER,
    [DESCRICAO] TEXT,
    [BATIDAS/FIO] INTEGER,
    [NE RESULTANTE] INTEGER,
    [SAP1] TEXT,
    [TRAMA REDUZIDO1] TEXT,
    [SGS1] TEXT,
    [SGS UN 2] TEXT,
    [DESCRICAO1] TEXT,
    [BATIDAS/FIO1] TEXT,
    [NE RESULTANTE1] TEXT,
    [CONS#TR/m] INTEGER,
    [SGS2] INTEGER,
    [QT#FIOS] INTEGER,
    [NE RESULTANTE2] INTEGER,
    [SGS3] INTEGER,
    [QT#FIOS1] TEXT,
    [NE RESULTANTE3] TEXT,
    [CONS#URD/m] TEXT,
    [BATIDA] INTEGER,
    [LARG#PENTE] INTEGER,
    [LARG#CRU] INTEGER,
    [PESO/m CRU] INTEGER,
    [Oz/jd2] INTEGER,
    [Peso/m2] TEXT,
    [LARGURA MIN] TEXT,
    [LARGURA] INTEGER,
    [LARGURA MAX] INTEGER,
    [SKEW MIN] INTEGER,
    [SKEW MAX] INTEGER,
    [URD#MIN] INTEGER,
    [URD#MAX] INTEGER,
    [TRAMA MIN] INTEGER,
    [TRAMA MAX] INTEGER,
    [VAR STR#MIN TRAMA] INTEGER,
    [VAR STR#MAX TRAMA] INTEGER,
    [VAR STR#MIN URD] INTEGER,
    [VAR STR#MAX URD] INTEGER,
    [PONTOS] INTEGER,
    [ENC#TEC#URDUME] INTEGER,
    [ENC# TEC#TRAMA] INTEGER,
    [ENC#ACAB URD] INTEGER,
    [ENC#ACAB TRAMA] INTEGER,
    [LAV#AMAC#URD] INTEGER,
    [LAV#AMAC#TRM] INTEGER,
    [LAV STONE] TEXT,
    [LAV STONE 1] INTEGER,
    [STRET LAV STONE] INTEGER,
    [COMPOSICAO] INTEGER,
    [TRAMA] INTEGER
);
CREATE INDEX idx_fichas_artigo ON tb_FICHAS(ARTIGO);
